version: "3.1"

services:
  ############################################
  # Database engine service PRD
  ############################################
  postgres_db_prod:
    container_name: postgres_prd
    image: postgres:16
    restart: always
    networks:
      - env_prod
    ports:
      - 5432:5432
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/postgres_data_prd:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
  ############################################
  # Database engine service PRE
  ############################################
  postgres_db_prep:
    container_name: postgres_pre
    image: postgres:16
    restart: always
    networks:
      - env_prep
    ports:
      - 4432:5432
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/postgres_data_pre:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
  ############################################
  #database admin service
  ############################################
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres_db_prod
      - postgres_db_prep
    networks:
      - env_prod
      - env_prep
    ports:
      - 9090:8080
  ############################################
  #Billin app backend service
  ############################################
  billingapp-back-prep:
    build:
      context: ./java
      args:
        - JAR_FILE=billing-pre.jar
    container_name: billingapp-back-prep
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - postgres_db_prep
    networks:
      - env_prep
    ports:
      - 7080:7080
  ############################################
  #Billin app backend service
  ############################################
  billingapp-back_prd:
    build:
      context: ./java
      args:
        - JAR_FILE=billing-prd.jar
    container_name: billingApp-back_prd
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - postgres_db_prod
    networks:
      - env_prod
    ports:
      - 8080:8080
  ############################################
  #Billing app frontend service
  ############################################
  billingapp-front_pre:
    build:
      context: ./angular
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 250M
        #recusos dedicados, mantiene los recursos disponibles del host para el contenedor
        reservations:
          cpus: "0.1"
          memory: 128M
    #container_name: billingApp-front
    depends_on:
      - billingapp-back-prep
    networks:
      - env_prep
    #rango de puertos para escalar
    ports:
      - 80:80
  ############################################
  #Billin app frontend service
  ############################################
  billingapp-front_prd:
    build:
      context: ./angular
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 250M
        #recusos dedicados, mantiene los recursos disponibles del host para el contenedor
        reservations:
          cpus: "0.1"
          memory: 128M
    #container_name: billingApp-front
    depends_on:
      - billingapp-back_prd
    networks:
      - env_prod
    #rango de puertos para escalar
    ports:
      - 81:81
networks:
  ############################################
  # Network service PRE
  ############################################
  env_prep:
    driver: bridge
    #activate ipv6
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    #IP Adress Manager
    ipam:
      driver: default
      config:
        - subnet: 172.16.235.0/24
          gateway: 172.16.235.1
        - subnet: "2001:3984:3989::/64"
          gateway: "2001:3984:3989::1"
  ############################################
  # Network service PRD
  ############################################
  env_prod:
    driver: bridge
    #activate ipv6
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    #IP Adress Manager
    ipam:
      driver: default
      config:
        - subnet: 172.16.232.0/24
          gateway: 172.16.232.1
        - subnet: "2001:3974:3979::/64"
          gateway: "2001:3974:3979::1"
